# Generated by Django 4.2.7 on 2023-12-30 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Criterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('parent_criterion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projekt.criterias')),
            ],
        ),
        migrations.CreateModel(
            name='DataWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('criteriaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.criterias')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionScenarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.IntegerField(blank=True, null=True, unique=True)),
                ('weightID', models.IntegerField(blank=True, null=True, unique=True)),
                ('submited', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_method', models.CharField(choices=[('GMM', 'Geometric Mean Method')], default='GMM', max_length=4)),
                ('aggregation_method', models.CharField(choices=[('AIP', 'Aggregation of individual priorities')], default='AIP', max_length=4)),
                ('completeness_required', models.BooleanField(default=True)),
                ('criteriasDone', models.BooleanField(default=False)),
                ('expertsDone', models.BooleanField(default=False)),
                ('scaleDone', models.BooleanField(default=False)),
                ('alternativesDone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioWeights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataWeights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.dataweights')),
                ('weightsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.decisionscenarios', to_field='weightID')),
            ],
        ),
        migrations.CreateModel(
            name='ModelScales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.models')),
                ('scaleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.scales')),
            ],
        ),
        migrations.CreateModel(
            name='ModelCriterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteriaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.criterias')),
                ('modelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.models')),
            ],
        ),
        migrations.CreateModel(
            name='ModelAlternatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.alternatives')),
                ('modelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.models')),
            ],
        ),
        migrations.CreateModel(
            name='Matrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('criteriaID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projekt.criterias')),
                ('expertID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projekt.experts')),
            ],
        ),
        migrations.CreateModel(
            name='MatriceElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('value', models.FloatField()),
                ('matrixID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.matrices')),
            ],
        ),
        migrations.AddField(
            model_name='decisionscenarios',
            name='modelID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projekt.models'),
        ),
        migrations.AddField(
            model_name='decisionscenarios',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DataMatrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.decisionscenarios', to_field='dataID')),
                ('matrixID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.matrices')),
            ],
        ),
        migrations.CreateModel(
            name='DataElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('value', models.FloatField()),
                ('dataWeightsID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projekt.dataweights')),
            ],
        ),
        migrations.CreateModel(
            name='ModelExperts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('expertID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.experts')),
                ('modelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.models')),
            ],
            options={
                'unique_together': {('modelID', 'expertID')},
            },
        ),
    ]
