# Generated by Django 4.2.7 on 2023-11-19 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Criterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_criterion', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Experts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_method', models.CharField(max_length=4)),
                ('aggregation_method', models.CharField(max_length=4)),
                ('completeness_required', models.BooleanField()),
                ('criteriasDone', models.BooleanField(default=False)),
                ('expertsDone', models.BooleanField(default=False)),
                ('scaleDone', models.BooleanField(default=False)),
                ('alternativesDone', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModelScales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.models')),
                ('scaleID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.scales')),
            ],
        ),
        migrations.CreateModel(
            name='ModelExperts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.experts')),
                ('modelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.models')),
            ],
        ),
        migrations.CreateModel(
            name='ModelCriterias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteriaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.criterias')),
                ('modelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.models')),
            ],
        ),
        migrations.CreateModel(
            name='ModelAlternatives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternativeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.alternatives')),
                ('modelID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.models')),
            ],
        ),
        migrations.CreateModel(
            name='Matrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowSize', models.IntegerField()),
                ('columnSize', models.IntegerField()),
                ('criteriaID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projekt.criterias')),
                ('expertID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projekt.experts')),
            ],
        ),
        migrations.CreateModel(
            name='MatriceElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('value', models.FloatField()),
                ('matrixID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.matrices')),
            ],
        ),
        migrations.CreateModel(
            name='DecisionScenarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.IntegerField(unique=True)),
                ('weightID', models.IntegerField(unique=True)),
                ('modelID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projekt.models')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataMatrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.decisionscenarios', to_field='dataID')),
                ('matrixID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.matrices')),
            ],
        ),
        migrations.CreateModel(
            name='WeightsData',
            fields=[
                ('weightsID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projekt.decisionscenarios', to_field='weightID')),
                ('size', models.IntegerField()),
                ('criteriaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.criterias')),
            ],
        ),
        migrations.CreateModel(
            name='DataElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('value', models.FloatField()),
                ('weightsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.weightsdata')),
            ],
        ),
    ]
