# Generated by Django 4.2.6 on 2023-11-09 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projekt", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Criterias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parent_criterion", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Models",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ranking_method", models.CharField(max_length=4)),
                ("aggregation_method", models.CharField(max_length=4)),
                ("completness_required", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="ModelExperts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expertID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projekt.experts",
                    ),
                ),
                (
                    "modelID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projekt.models"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModelCriterias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criteriaID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projekt.criterias",
                    ),
                ),
                (
                    "modelID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projekt.models"
                    ),
                ),
            ],
        ),
    ]
