# Generated by Django 4.2.6 on 2023-12-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projekt", "0002_alter_criterias_parent_criterion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisionscenarios",
            name="submited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="decisionscenarios",
            name="url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
