# Generated by Django 4.2.6 on 2023-11-09 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projekt", "0002_criterias_models_modelexperts_modelcriterias"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeightData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Weights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeightsCriterias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criteriaID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projekt.criterias",
                    ),
                ),
                (
                    "weightDataID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projekt.weightdata",
                    ),
                ),
                (
                    "weightID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projekt.weights",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Matrices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rowSize", models.IntegerField()),
                ("columnSize", models.IntegerField()),
                (
                    "criteriaID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projekt.criterias",
                    ),
                ),
                (
                    "expertID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projekt.experts",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MatriceElements",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                ("value", models.FloatField()),
                (
                    "matrixID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projekt.matrices",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DecisionScenarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dataID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projekt.data"
                    ),
                ),
                (
                    "modelID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projekt.models"
                    ),
                ),
                (
                    "weightID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projekt.weights",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataMatrices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "MatrixID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projekt.matrices",
                    ),
                ),
                (
                    "dataID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="projekt.data"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DataElement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expertlDorXValue", models.IntegerField()),
                ("value", models.FloatField()),
                (
                    "weightDataID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projekt.weightdata",
                    ),
                ),
            ],
        ),
    ]
