# Generated by Django 4.2.6 on 2023-12-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projekt", "0003_decisionscenarios_submited_decisionscenarios_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="decisionscenarios",
            name="password",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
