# Generated by Django 4.2.7 on 2023-11-12 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0003_data_weightdata_weights_weightscriterias_matrices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertlDorXValue', models.IntegerField()),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='weightscriterias',
            name='Size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weightscriterias',
            name='weightDataID',
            field=models.IntegerField(unique=True),
        ),
        migrations.DeleteModel(
            name='DataElement',
        ),
        migrations.DeleteModel(
            name='WeightData',
        ),
        migrations.AddField(
            model_name='dataelements',
            name='weightDataID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.weightscriterias', to_field='weightDataID'),
        ),
    ]
