# Generated by Django 4.2.6 on 2023-12-11 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projekt", "0004_decisionscenarios_password"),
    ]

    operations = [

        migrations.AddField(
            model_name="experts",
            name="user",
            field=models.OneToOneField(
                default=0,
                on_delete=django.db.models.deletion.DO_NOTHING,
                primary_key=False,
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="experts",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
