# Generated by Django 4.2.7 on 2023-12-12 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projekt', '0005_remove_experts_id_experts_user_alter_experts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experts',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
