# Generated by Django 4.2.7 on 2023-12-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0008_modelexperts_done_alter_alternatives_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='aggregation_method',
            field=models.CharField(choices=[('AIP', 'Aip')], default='AIP', max_length=4),
        ),
        migrations.AlterField(
            model_name='models',
            name='ranking_method',
            field=models.CharField(choices=[('EVM', 'Active')], default='EVM', max_length=4),
        ),
    ]
