# Generated by Django 4.2.7 on 2023-11-19 13:45

from django.db import migrations


def insert_root(apps, schema_editor):
    Criterias = apps.get_model("projekt", "Criterias")
    root = Criterias(pk=0, name="Root", description="Root Criterium")
    root.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0008_alter_criterias_parent_criterion'),
    ]

    operations = [
        migrations.RunPython(insert_root)
    ]
