# Generated by Django 4.2.7 on 2023-12-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0009_alter_models_aggregation_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='models',
            name='aggregation_method',
            field=models.CharField(choices=[('AIP', 'Aggregation of individual priorities')], default='AIP', max_length=4),
        ),
        migrations.AlterField(
            model_name='models',
            name='completeness_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='models',
            name='ranking_method',
            field=models.CharField(choices=[('GMM', 'Geometric Mean Method')], default='GMM', max_length=4),
        ),
    ]
