# Generated by Django 4.2.7 on 2023-12-28 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projekt', '0013_dataweights_scenarioweights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataelements',
            name='dataWeightsID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='projekt.dataweights'),
        ),
    ]
